baseUrl = 'https://flutter-explained.dev/'
languageCode = 'en-us'
title = 'Max Weber - Developer, Publisher and Father'

theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
social = true
env = "production"
title = "Max Weber"
description = "Developer, Publisher and Father"
keywords = ["Blog", "Portfolio", "PaperMod"]
author = "Max Weber"
images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = true
title = "Max Weber"
subtitle = "Code is only a tool \n\n Website is Work in Progress 🚧"
imageUrl = "profile_max.webp"
imageWidth = 120
imageHeight = 120
imageTitle = "Max Weber - Developer"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Podcast"
url = "https://podcast.flutter-explained.dev"

[[params.profileMode.buttons]]
name = "Bitcoin Tracker App"
url = "https://play.google.com/store/apps/details?id=dev.flutterexp.bitcoinTracker"

[[params.profileMode.buttons]]
name = "YouTube"
url = "https://youtube.com/flutterexplained"

[params.homeInfoParams]
Title = "Hi there \U0001F44B"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "x"
url = "https://x.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/3690032/max-weber"

[[params.socialIcons]]
name = "github"
url = "https://github.com/md-weber"

[params.analytics.google]
SiteVerificationTag = ""

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/md-weber/website/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]


[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 20

# [[menu.main]]
# identifier = "example"
# name = "example.org"
# url = "https://example.org"
# weight = 30

[markup.highlight]
noClasses = false

[privacy.youtube]
disable = false
privacyEnhanced = true
